name: Python package
on: push
jobs:
 build:
  runs-on: ubuntu-latest
  steps: 
  - uses: actions/checkout@v4
  - name: setup Python
  - uses: actions/setup-python@v4
    with:
      python-vrsion: '3.x'
      architecture: 'x.64'
  - name: Display python version
    run: python -c "import sys; print(sys.version)"
