name: shcon
on: push
jobs:
  run_example_job:
    runs-on: ubuntu-latest
     
    steps:
    - name: run a checkout
      uses: actions/checkout@v4
    - name: run shell commands  
      run: |
        ls ${{ github.workspace }}
        
    - name: copy file to server
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER_NAME }}
        key: ${{ secrets.Private_Key }}
        port: ${{ secrets.PORT }}
        source: ${{ github.workspace }}/first.sh
        target: /home/ubuntu/
        
    - name: print out example job
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER_NAME }}
        key: ${{ secrets.Private_Key }}
        port: ${{ secrets.PORT }}
         
        run: |
          pwd
          sh /home/ubuntu/github/workspace/first.sh

        
      
          
          
  
