name: shcon
on: push
jobs:
  run_example_job:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - name: print out example job
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER_NAME }}
        key: ${{ secrets.Private_Key }}
        port: ${{ secrets.PORT }}
        command_timeout: 30m
        script:  
           touch new1.txt
